workspace(name = "com_google_ddex_parser")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.12.0-rc-2",
    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0-rc2/protobuf-cpp-3.12.0-rc-2.zip"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()