package com.google.ddex.xsdtoproto;

import com.google.common.flogger.FluentLogger;

import java.util.ArrayList;
import java.util.List;

/**
 * The XsdParseReporter stores any warnings generated by the {@link com.google.ddex.xsdtoproto.XsdParser}. The reporter should be
 * instantiated and passed in as a parameter to the parse function call.
 */
public class XsdParseReporter {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    List<String> processedSchemaNamespaces;
    List<String> warnings;

    /**
     * Constructor.
     */
    public XsdParseReporter() {
        processedSchemaNamespaces = new ArrayList<>();
        warnings = new ArrayList<>();
    }

    /**
     * Record a schema namespace that has been parsed
     * @param namespace the namespace of the schema being processed
     */
    public void addProcessedSchema(String namespace) {
        logger.atInfo().log("Processed " + namespace);
        processedSchemaNamespaces.add(namespace);
    }

  /**
   * Record a warning.
   * @param warning The warning
   */
  public void addWarning(String warning) {
        logger.atWarning().log(warning);
        warnings.add(warning);
    }
}
