package com.google.ddex.xmltoproto;

import com.google.common.flogger.FluentLogger;

import java.util.ArrayList;
import java.util.List;

/**
 * The MessageParseReporter stores any warnings generated by the {@link
 * com.google.ddex.xmltoproto.MessageParser}. The reporter should be instantiated and passed in as a
 * parameter to the parse function call.
 */
public interface MessageParserReporter {
  void addWarning(String warning);
  void addLog(String log);

  public static class DefaultMessageParserReporter implements MessageParserReporter {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    List<String> warnings;
    List<String> logs;

    /** Instantiates a new Message parse reporter. */
    public DefaultMessageParserReporter() {
      warnings = new ArrayList<>();
      logs = new ArrayList<>();
    }

    /**
     * Record a warning.
     *
     * @param warning The warning
     */
    public void addWarning(String warning) {
      logger.atWarning().log(warning);
      warnings.add(warning);
    }

    /**
     * Record a log.
     *
     * @param log The warning
     */
    public void addLog(String log) {
      logger.atFine().log(log);
      logs.add(log);
    }
  }
}
