package com.google.ddex.xmltoproto;

import com.google.common.flogger.FluentLogger;

import java.util.ArrayList;
import java.util.List;

/** The MessageParseReporter stores any warnings generated by the {@link com.google.ddex.xmltoproto.MessageParser}. The reporter should be instantiated and passed in as a parameter to the parse function call. */
public class MessageParseReporter {
  private static final FluentLogger logger = FluentLogger.forEnclosingClass();

  List<String> warnings;

  /** Instantiates a new Message parse reporter. */
  public MessageParseReporter() {
    warnings = new ArrayList<>();
  }

  /**
   * Record a warning.
   *
   * @param warning The warning
   */
  public void addWarning(String warning) {
    logger.atWarning().log(warning);
    warnings.add(warning);
  }
}
